<?php

/**
 * PluginBonussalaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBonussalaryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginBonussalaryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBonussalary');
    }
}