<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tenant', 'doctrine');

/**
 * BaseOhrmTenant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                       $id                                             Type: integer(4), primary key
 * @property string                                    $tenant_name                                    Type: string(100)
 * @property string                                    $tenant_attribute                               Type: string(100)
 * @property Doctrine_Collection|HsHrEmpBonussalary[]  $HsHrEmpBonussalary                             
 * @property Doctrine_Collection|OhrmUser[]            $OhrmUser                                       
 *  
 * @method int                                         getId()                                         Type: integer(4), primary key
 * @method string                                      getTenantName()                                 Type: string(100)
 * @method string                                      getTenantAttribute()                            Type: string(100)
 * @method Doctrine_Collection|HsHrEmpBonussalary[]    getHsHrEmpBonussalary()                         
 * @method Doctrine_Collection|OhrmUser[]              getOhrmUser()                                   
 *  
 * @method OhrmTenant                                  setId(int $val)                                 Type: integer(4), primary key
 * @method OhrmTenant                                  setTenantName(string $val)                      Type: string(100)
 * @method OhrmTenant                                  setTenantAttribute(string $val)                 Type: string(100)
 * @method OhrmTenant                                  setHsHrEmpBonussalary(Doctrine_Collection $val) 
 * @method OhrmTenant                                  setOhrmUser(Doctrine_Collection $val)           
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTenant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_tenant');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tenant_name', 'string', 100, array(
             'type' => 'string',
             ));
        $this->hasColumn('tenant_attribute', 'string', 100, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bonussalary', array(
             'local' => 'id',
             'foreign' => 'tenant_id'));

        $this->hasMany('SystemUser', array(
             'local' => 'id',
             'foreign' => 'tenant_id'));
    }
}