<?php

/**
 * PluginTenantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTenantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginTenantTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTenant');
    }
}