<?php

/**
 * BonussalaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BonussalaryTable extends PluginBonussalaryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return BonussalaryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bonussalary');
    }
}