<?php

/**
 * BaseBonussalary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $id                        Type: integer(7), primary key
 * @property int          $employee_id               Type: integer(7)
 * @property int          $tenant_id                 Type: integer(7)
 * @property int          $year                      Type: integer(7)
 * @property int          $value                     Type: integer(7)
 * @property Employee     $Employee                  
 * @property Tenant       $Tenant                    
 *  
 * @method int            getId()                    Type: integer(7), primary key
 * @method int            getEmployeeId()            Type: integer(7)
 * @method int            getTenantId()              Type: integer(7)
 * @method int            getYear()                  Type: integer(7)
 * @method int            getValue()                 Type: integer(7)
 * @method Employee       getEmployee()              
 * @method Tenant         getTenant()                
 *  
 * @method Bonussalary    setId(int $val)            Type: integer(7), primary key
 * @method Bonussalary    setEmployeeId(int $val)    Type: integer(7)
 * @method Bonussalary    setTenantId(int $val)      Type: integer(7)
 * @method Bonussalary    setYear(int $val)          Type: integer(7)
 * @method Bonussalary    setValue(int $val)         Type: integer(7)
 * @method Bonussalary    setEmployee(Employee $val) 
 * @method Bonussalary    setTenant(Tenant $val)     
 *  
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBonussalary extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_bonussalary');
        $this->hasColumn('id', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 7,
             ));
        $this->hasColumn('emp_id', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('tenant_id', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('year', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
        $this->hasColumn('value', 'integer', 7, array(
             'type' => 'integer',
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_id',
             'foreign' => 'emp_number'));

        $this->hasOne('Tenant', array(
             'local' => 'tenant_id',
             'foreign' => 'id'));
    }
}